### ISSUE TITLE
DAEValidatorLibrary is built and linked against but not installed

### ISSUE THREAD

**Issue by hobbes1069** [KhronosGroup/OpenCOLLADA#573]
Which gives the following error in the Fedora update system:

```
results:
- arch: x86_64
  checkname: dist.rpmdeplint
  item: openCOLLADA-1.6.62-1.fc28
  outcome: FAILED
  scenario: x86_64
  type: koji_build


nothing provides libDAEValidatorLibrary.so()(64bit) needed by openCOLLADA-utils-1.6.62-1.fc28.x86_64
nothing provides libDAEValidatorLibrary.so()(64bit) needed by openCOLLADA-utils-1.6.62-1.fc28.x86_64
```
